export const onlineUsersSectionUsers = [
  { name: 'User 1', imageUrl: 'avatar1.jpg' },
  { name: 'User 2', imageUrl: 'avatar2.jpg' },
  { name: 'User 3', imageUrl: 'avatar3.jpg' },
  { name: 'User 4', imageUrl: 'avatar4.jpg' },
  { name: 'User 5', imageUrl: 'avatar4.jpg' },
  { name: 'User 6', imageUrl: 'avatar4.jpg' },
  { name: 'User 7', imageUrl: 'avatar4.jpg' },
  { name: 'User 8', imageUrl: 'avatar4.jpg' },
  { name: 'User 9', imageUrl: 'avatar4.jpg' },
  { name: 'User 10', imageUrl: 'avatar4.jpg' },
  { name: 'User 11', imageUrl: 'avatar4.jpg' },
  { name: 'User 12', imageUrl: 'avatar4.jpg' },
  { name: 'User 13', imageUrl: 'avatar4.jpg' },
  { name: 'User 14', imageUrl: 'avatar4.jpg' },
  { name: 'User 15', imageUrl: 'avatar4.jpg' },
  { name: 'User 16', imageUrl: 'avatar4.jpg' },
  { name: 'User 17', imageUrl: 'avatar4.jpg' },

  { name: 'User 2', imageUrl: 'avatar2.jpg' },
  { name: 'User 3', imageUrl: 'avatar3.jpg' },
  { name: 'User 4', imageUrl: 'avatar4.jpg' },
  { name: 'User 5', imageUrl: 'avatar4.jpg' },
  { name: 'User 6', imageUrl: 'avatar4.jpg' },
  { name: 'User 7', imageUrl: 'avatar4.jpg' },
  { name: 'User 8', imageUrl: 'avatar4.jpg' },
  { name: 'User 9', imageUrl: 'avatar4.jpg' },
  { name: 'User 10', imageUrl: 'avatar4.jpg' },
  { name: 'User 11', imageUrl: 'avatar4.jpg' },
  { name: 'User 12', imageUrl: 'avatar4.jpg' },
  { name: 'User 13', imageUrl: 'avatar4.jpg' },
  { name: 'User 14', imageUrl: 'avatar4.jpg' },
  { name: 'User 15', imageUrl: 'avatar4.jpg' },
  { name: 'User 16', imageUrl: 'avatar4.jpg' },
  { name: 'User 17', imageUrl: 'avatar4.jpg' },

  { name: 'User 5', imageUrl: 'avatar4.jpg' },
  { name: 'User 6', imageUrl: 'avatar4.jpg' },
  { name: 'User 7', imageUrl: 'avatar4.jpg' },
  { name: 'User 8', imageUrl: 'avatar4.jpg' },
  { name: 'User 9', imageUrl: 'avatar4.jpg' },
  { name: 'User 10', imageUrl: 'avatar4.jpg' },
  { name: 'User 11', imageUrl: 'avatar4.jpg' },
  { name: 'User 12', imageUrl: 'avatar4.jpg' },
  { name: 'User 13', imageUrl: 'avatar4.jpg' },
  { name: 'User 14', imageUrl: 'avatar4.jpg' },
  { name: 'User 15', imageUrl: 'avatar4.jpg' },
  { name: 'User 16', imageUrl: 'avatar4.jpg' },
  { name: 'User 17', imageUrl: 'avatar4.jpg' },
  // Add more users as needed
];
