enum RouterPaths {
  Home = '/',
  Login = '/login',
  Registration = '/registration',
  // RegistrationCompany = '/RegistrationCompanyInformation',
  CreateNewPassword = '/create-new-password',
  ResetPassword = '/reset-password',
  NotFound = '*',
  Dashboard = '/dashboard',
  Devices = '/devices',
  UserAuthentications = '/user-authentications',
  Venues = '/venues',
  Events = '/events',
  EventSchedules = '/event-schedules',
  Tickets = '/tickets',
  TicketOrders = '/ticket-orders',
  Guests = '/guests',
  SessionToken = '/session-token',
  AuditTrail = '/audit-trail',
  Users = '/users',
  UserList = '/user-list',
  Roles = '/roles',
  Groups = '/groups',
  EventTypes = '/event-types',
  EventGenres = '/event-genres',
  Addresses = '/addresses',
  Sales = '/sales',
  Settings = '/settings',
  Fees = '/fees',
  Counterparties = '/counterparties',
  CommissionRules = '/commission-rules',
}

export default RouterPaths;
