name: Build and Deploy
on:
  pull_request:
    branches:
      - staging
    types: [closed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Build and List Directory
        run: |
          yarn build
          echo "Listing current directory contents after build..."
          ls -al

      - name: Deploy to Server
        if: success() && github.event.pull_request.merged == true
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
          port: 22
          source: "build/"
          target: "/home/project"
